### ISSUE TITLE
CORS Error on Facebook/Instagram Embed

### ISSUE THREAD

**Issue by russelshane** [Embedigo/editorjs-embedigo#1]
Hi, I'm getting a cors error from your API when I'm trying to embed a post from Facebook or Instagram, other services seem to be working fine. Thanks!

**Comment by hotrush** [comment]
Hello @russelshane, facebook revoked my access to oembed feature by some reason. Sent a new request to them and waiting for response.

**Comment by hotrush** [comment]
resolved

**Comment by russelshane** [comment]
Thanks! embedigo's been really helpful. Hate the embed that comes out of the box in EditorJS.

**Comment by hotrush** [comment]
Yeah, it uses native embeds that are not always reliable. Thank
